"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BinAnd = exports.BinXor = exports.BinOr = exports.Shr = exports.Shl = exports.Mod = exports.Div = exports.Mul = exports.Sub = exports.Add = exports.Literal = exports.ReturnStmt = exports.IncStmt = exports.DecStmt = exports.ContinueStmt = exports.BreakStmt = void 0;
var statements_1 = require("./statements");
Object.defineProperty(exports, "BreakStmt", { enumerable: true, get: function () { return statements_1.BreakStmt; } });
Object.defineProperty(exports, "ContinueStmt", { enumerable: true, get: function () { return statements_1.ContinueStmt; } });
Object.defineProperty(exports, "DecStmt", { enumerable: true, get: function () { return statements_1.DecStmt; } });
Object.defineProperty(exports, "IncStmt", { enumerable: true, get: function () { return statements_1.IncStmt; } });
Object.defineProperty(exports, "ReturnStmt", { enumerable: true, get: function () { return statements_1.ReturnStmt; } });
var expressions_1 = require("./expressions");
Object.defineProperty(exports, "Literal", { enumerable: true, get: function () { return expressions_1.Literal; } });
Object.defineProperty(exports, "Add", { enumerable: true, get: function () { return expressions_1.Add; } });
Object.defineProperty(exports, "Sub", { enumerable: true, get: function () { return expressions_1.Sub; } });
Object.defineProperty(exports, "Mul", { enumerable: true, get: function () { return expressions_1.Mul; } });
Object.defineProperty(exports, "Div", { enumerable: true, get: function () { return expressions_1.Div; } });
Object.defineProperty(exports, "Mod", { enumerable: true, get: function () { return expressions_1.Mod; } });
Object.defineProperty(exports, "Shl", { enumerable: true, get: function () { return expressions_1.Shl; } });
Object.defineProperty(exports, "Shr", { enumerable: true, get: function () { return expressions_1.Shr; } });
Object.defineProperty(exports, "BinOr", { enumerable: true, get: function () { return expressions_1.BinOr; } });
Object.defineProperty(exports, "BinXor", { enumerable: true, get: function () { return expressions_1.BinXor; } });
Object.defineProperty(exports, "BinAnd", { enumerable: true, get: function () { return expressions_1.BinAnd; } });
